# Generated by Django 6.0.2 on 2026-02-15 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pochta', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('full_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regions', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('describe', models.TextField()),
                ('price', models.DecimalField(decimal_places=1, max_digits=11)),
                ('title', models.CharField(max_length=200)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.account')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads_by_category', to='firstapp.category')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.region')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('category_job', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=11)),
                ('tipwork', models.CharField(max_length=100)),
                ('tipzanyatosti', models.CharField(max_length=100)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.account')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.category')),
                ('reklama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.ad')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.region')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('tip', models.CharField(max_length=100)),
                ('describe', models.TextField()),
                ('area', models.FloatField()),
                ('rooms', models.IntegerField()),
                ('floor', models.FloatField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.account')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.category')),
                ('reklama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.ad')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.region')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('mileage', models.FloatField()),
                ('fuel_type', models.CharField(max_length=50)),
                ('transmission', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('kolichestvo_xozyayev', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.account')),
                ('reklama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.ad')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.category')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.region')),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(max_length=100)),
                ('poroda', models.CharField(max_length=100)),
                ('age', models.FloatField()),
                ('color', models.CharField(max_length=50)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.account')),
                ('reklama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.ad')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.category')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.region')),
            ],
        ),
    ]
